### ISSUE TITLE
Question about CGAL import

### ISSUE THREAD

**Issue by DigitCell** [LokiResearch/arrangement-2d-js#1]
Some time ago try to use CGAL arrangement module in my project c++ with export to webassembly, but can find solution.
CGAL try to use gmp lib and as understand this produce a lot of errors when try to compile module to JS, in plane c++ all work well.
Question how to adopt your solution in c++ program with em compiler?
take part from cmake or need some additional classes as gpc.c included?

**Comment by minitoine** [comment]
Hello,
To build this specific projet, I use CGAL source code without activating GMP. If you look at the install script (for example the ci workflow), you'll see that i'm downloading and extracting CGAL and boost archives, and I call the CGAL classes I need from my C++ code.
gpc.c is used internally in my polygon.cpp class and has nothing to do with CGAL.

If you need GMP to build your project, then you need to tweak the source code (mostly FPU related files), for that, have a look at https://github.com/marcosscriven/cgaljs, and the associated forks.
